# Generated by Django 2.1 on 2018-08-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_order', models.IntegerField()),
                ('chapter_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
                ('length', models.IntegerField()),
                ('path', models.FileField(upload_to='audiofiles')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('minutes', models.IntegerField()),
                ('title', models.CharField(max_length=250)),
                ('book_title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_id', models.IntegerField()),
                ('name', models.CharField(max_length=250)),
            ],
        ),
    ]
