# Generated by Django 2.1 on 2018-08-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.FileField(default=' ', upload_to='audiofiles'),
            preserve_default=False,
        ),
    ]
