# Generated by Django 2.1 on 2018-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_audio_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='path',
            field=models.CharField(max_length=300),
        ),
    ]
